news_homepage:
    path:     /hello/{name}
    defaults: { _controller: NewsBundle:Default:index }

news_main:
    path:     /news
    defaults: { _controller: NewsBundle:News:index }

newsa_main:
    path:     /news/{slug}
    defaults: { _controller: NewsBundle:News:show }
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    type: sonata_admin
    prefix: /admin